component: cart
params: "REDIS_HOST:prod.elasticache.endpoint,CATALOGUE_HOST:catalogue,CATALOGUE_PORT:8080"

resources:
   limits:
     cpu: 300m
     memory: 350Mi
   requests:
     cpu: 200m
     memory: 256Mi